  networks:
    express-network:
    mongodb-network:   
    redis-network:    

  services:

    api:
      image: doconnor/movies-api:1.0
      container_name: movies-api
      ports:
        - '9000:9000'
      environment:
        MONGODB_URI: mongodb://admin:password@mongodb:27017
        REDIS_URI: redis://redis:6379
        ENABLE_WRITING_HANDLERS: 'false'
      networks:
        - mongodb-network
        - redis-network
      depends_on:
        - mongodb
        - redis

    mongodb:
      container_name: mongodb
      image: mongo:8.0-rc
      restart: always
      environment: 
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
      ports:
        - '27017:27017'
      networks:
        - mongodb-network
        - express-network
      

    redis:
      container_name: redis
      image: redis:alpine
      restart: always
      ports:
      - '6379:6379'
      networks:
        - redis-network

    mongo-express:
      container_name: express
      image: mongo-express:1.0-20-alpine3.19
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_MONGODB_SERVER: mongodb
      networks:
        - express-network
      depends_on:
        - mongodb

    seeder:
      container_name: seeder
      build:
        context: .
        dockerfile: Dockerfile-seeder
      restart: always
      depends_on:
        - mongodb
      environment:
        MONGODB_URI: mongodb://admin:password@mongodb:27017 
      networks:
        - mongodb-network